name: flutter_weather
description: 小鸭天气
version: 1.0.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  shared_preferences: ^2.2.2 # 轻量级本地键值对存储，可以缓存数据
  geolocator: ^11.0.0 # 位置服务
  flutter_cache_manager: ^3.3.1
  # device_info: ^2.0.3
  intl: ^0.18.1
  url_launcher: ^6.2.5
  # cached_network_image: ^3.3.1
  # connectivity: ^3.0.6
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  # package_info: ^2.0.2
  rxdart: ^0.27.7
  html: ^0.15.4
  webview_flutter: ^4.7.0
  flutter_colorpicker: ^1.0.3
  # dragable_flutter_list: 1.0.2
  flutter_reorderable_list: ^1.3.1
  flutter_linkify: ^6.0.0
  # image_gallery_saver: ^2.0.3
  # esys_flutter_share: 1.0.2
  csv: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  retry: ^3.1.2
  # wallpaper_manager: ^1.0.10
  # path_provider: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # 图片
    - images/0.png
    - images/0_night.png
    - images/1.png
    - images/1_night.png
    - images/2.png
    - images/3.png
    - images/4.png
    - images/5.png
    - images/6.png
    - images/7.png
    - images/8.png
    - images/9.png
    - images/10.png
    - images/11.png
    - images/12.png
    - images/13.png
    - images/14.png
    - images/15.png
    - images/16.png
    - images/17.png
    - images/18.png
    - images/19.png
    - images/20.png
    - images/21.png
    - images/22.png
    - images/23.png
    - images/24.png
    - images/25.png
    - images/26.png
    - images/27.png
    - images/28.png
    - images/29.png
    - images/30.png
    - images/53.png
    - images/54.png
    - images/55.png
    - images/56.png
    - images/301.png
    - images/999.png
    - images/splash.png
    - images/air_soft_1.png
    - images/air_soft_2.png
    - images/air_soft_3.png
    - images/air_soft_4.png
    - images/air_soft_5.png
    - images/air_soft_6.png
    - images/air_soft_7.png
    - images/air_soft_8.png
    - images/drawer_bg.png
    - images/duck_bg.png
    - images/ic_boat_day.png
    - images/ic_boat_night.png
    - images/ic_cloud.png
    - images/ic_fog_ground.png
    - images/ic_hail_ground.png
    - images/ic_haze_ground.png
    - images/ic_rain_ground.png
    - images/ic_sanstorm_ground.png
    - images/ic_snow_ground.png
    - images/hammer_share1.jpg
    - images/hammer_share2.jpg
    - images/hammer_share3.jpg

    # assets
    - assets/china-city-list.csv
    - assets/jlqjjt.ttf

  fonts:
    - family: JLQJJT
      fonts:
        - asset: assets/jlqjjt.ttf
